=begin
#Cisco Intersight

#Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2021-10-20T11:22:53Z.

The version of the OpenAPI document: 1.0.9-4870
Contact: intersight@cisco.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.1

=end

require 'date'
require 'time'

module IntersightClient
  # Definition of the list of properties defined in 'compute.ServerSetting', excluding properties defined in parent classes.
  class ComputeServerSettingAllOf
    # The fully-qualified name of the instantiated, concrete type. This property is used as a discriminator to identify the type of the payload when marshaling and unmarshaling data.
    attr_accessor :class_id

    # The fully-qualified name of the instantiated, concrete type. The value should be the same as the 'ClassId' property.
    attr_accessor :object_type

    # User configured state of the locator LED for the server. * `None` - No operation property for locator led. * `On` - The Locator Led is turned on. * `Off` - The Locator Led is turned off.
    attr_accessor :admin_locator_led_state

    # User configured power state of the server. * `Policy` - Power state is set to the default value in the policy. * `PowerOn` - Power state of the server is set to On. * `PowerOff` - Power state is the server set to Off. * `PowerCycle` - Power state the server is reset. * `HardReset` - Power state the server is hard reset. * `Shutdown` - Operating system on the server is shut down. * `Reboot` - Power state of IMC is rebooted.
    attr_accessor :admin_power_state

    attr_accessor :certificates_action

    # The allowed actions on the CMOS Reset. * `Ready` - CMOS Reset operation is allowed to be done on the server in this state. * `Pending` - This indicates that the previous CMOS Reset operation on this server has not completed due to a pending power cycle. CMOS Reset operation cannot be done on the server when in this state. * `Reset` - The value that the UI/API needs to provide to trigger a CMOS Reset operation on a server.
    attr_accessor :cmos_reset

    # The configured state of these settings in the target server. The value is any one of Applied, Applying, Failed. Applied - This state denotes that the settings are applied successfully in the target server. Applying - This state denotes that the settings are being applied in the target server. Failed - This state denotes that the settings could not be applied in the target server. * `Applied` - User configured settings are in applied state. * `Applying` - User settings are being applied on the target server. * `Failed` - User configured settings could not be applied.
    attr_accessor :config_state

    # The allowed actions on the Front Panel Lock. * `Unlock` - Front Panel of the server is set to Unlocked state. * `Lock` - Front Panel of the server is set to Locked state.
    attr_accessor :front_panel_lock_state

    # The property used to identify the name of the server it is associated with.
    attr_accessor :name

    # The name of the device chosen by user for configuring One-Time Boot device.
    attr_accessor :one_time_boot_device

    attr_accessor :persistent_memory_operation

    attr_accessor :server_config

    attr_accessor :storage_controller_operation

    attr_accessor :storage_physical_drive_operation

    attr_accessor :storage_virtual_drive_operation

    attr_accessor :locator_led

    attr_accessor :registered_device

    attr_accessor :running_workflow

    attr_accessor :server

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'class_id' => :'ClassId',
        :'object_type' => :'ObjectType',
        :'admin_locator_led_state' => :'AdminLocatorLedState',
        :'admin_power_state' => :'AdminPowerState',
        :'certificates_action' => :'CertificatesAction',
        :'cmos_reset' => :'CmosReset',
        :'config_state' => :'ConfigState',
        :'front_panel_lock_state' => :'FrontPanelLockState',
        :'name' => :'Name',
        :'one_time_boot_device' => :'OneTimeBootDevice',
        :'persistent_memory_operation' => :'PersistentMemoryOperation',
        :'server_config' => :'ServerConfig',
        :'storage_controller_operation' => :'StorageControllerOperation',
        :'storage_physical_drive_operation' => :'StoragePhysicalDriveOperation',
        :'storage_virtual_drive_operation' => :'StorageVirtualDriveOperation',
        :'locator_led' => :'LocatorLed',
        :'registered_device' => :'RegisteredDevice',
        :'running_workflow' => :'RunningWorkflow',
        :'server' => :'Server'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'class_id' => :'String',
        :'object_type' => :'String',
        :'admin_locator_led_state' => :'String',
        :'admin_power_state' => :'String',
        :'certificates_action' => :'CertificatemanagementCertificateBase',
        :'cmos_reset' => :'String',
        :'config_state' => :'String',
        :'front_panel_lock_state' => :'String',
        :'name' => :'String',
        :'one_time_boot_device' => :'String',
        :'persistent_memory_operation' => :'ComputePersistentMemoryOperation',
        :'server_config' => :'ComputeServerConfig',
        :'storage_controller_operation' => :'ComputeStorageControllerOperation',
        :'storage_physical_drive_operation' => :'ComputeStoragePhysicalDriveOperation',
        :'storage_virtual_drive_operation' => :'ComputeStorageVirtualDriveOperation',
        :'locator_led' => :'EquipmentLocatorLedRelationship',
        :'registered_device' => :'AssetDeviceRegistrationRelationship',
        :'running_workflow' => :'WorkflowWorkflowInfoRelationship',
        :'server' => :'ComputePhysicalRelationship'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'certificates_action',
        :'persistent_memory_operation',
        :'server_config',
        :'storage_controller_operation',
        :'storage_physical_drive_operation',
        :'storage_virtual_drive_operation',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `IntersightClient::ComputeServerSettingAllOf` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `IntersightClient::ComputeServerSettingAllOf`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'class_id')
        self.class_id = attributes[:'class_id']
      else
        self.class_id = 'compute.ServerSetting'
      end

      if attributes.key?(:'object_type')
        self.object_type = attributes[:'object_type']
      else
        self.object_type = 'compute.ServerSetting'
      end

      if attributes.key?(:'admin_locator_led_state')
        self.admin_locator_led_state = attributes[:'admin_locator_led_state']
      else
        self.admin_locator_led_state = 'None'
      end

      if attributes.key?(:'admin_power_state')
        self.admin_power_state = attributes[:'admin_power_state']
      else
        self.admin_power_state = 'Policy'
      end

      if attributes.key?(:'certificates_action')
        self.certificates_action = attributes[:'certificates_action']
      end

      if attributes.key?(:'cmos_reset')
        self.cmos_reset = attributes[:'cmos_reset']
      else
        self.cmos_reset = 'Ready'
      end

      if attributes.key?(:'config_state')
        self.config_state = attributes[:'config_state']
      else
        self.config_state = 'Applied'
      end

      if attributes.key?(:'front_panel_lock_state')
        self.front_panel_lock_state = attributes[:'front_panel_lock_state']
      else
        self.front_panel_lock_state = 'Unlock'
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'one_time_boot_device')
        self.one_time_boot_device = attributes[:'one_time_boot_device']
      end

      if attributes.key?(:'persistent_memory_operation')
        self.persistent_memory_operation = attributes[:'persistent_memory_operation']
      end

      if attributes.key?(:'server_config')
        self.server_config = attributes[:'server_config']
      end

      if attributes.key?(:'storage_controller_operation')
        self.storage_controller_operation = attributes[:'storage_controller_operation']
      end

      if attributes.key?(:'storage_physical_drive_operation')
        self.storage_physical_drive_operation = attributes[:'storage_physical_drive_operation']
      end

      if attributes.key?(:'storage_virtual_drive_operation')
        self.storage_virtual_drive_operation = attributes[:'storage_virtual_drive_operation']
      end

      if attributes.key?(:'locator_led')
        self.locator_led = attributes[:'locator_led']
      end

      if attributes.key?(:'registered_device')
        self.registered_device = attributes[:'registered_device']
      end

      if attributes.key?(:'running_workflow')
        self.running_workflow = attributes[:'running_workflow']
      end

      if attributes.key?(:'server')
        self.server = attributes[:'server']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @class_id.nil?
        invalid_properties.push('invalid value for "class_id", class_id cannot be nil.')
      end

      if @object_type.nil?
        invalid_properties.push('invalid value for "object_type", object_type cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @class_id.nil?
      class_id_validator = EnumAttributeValidator.new('String', ["compute.ServerSetting"])
      return false unless class_id_validator.valid?(@class_id)
      return false if @object_type.nil?
      object_type_validator = EnumAttributeValidator.new('String', ["compute.ServerSetting"])
      return false unless object_type_validator.valid?(@object_type)
      admin_locator_led_state_validator = EnumAttributeValidator.new('String', ["None", "On", "Off"])
      return false unless admin_locator_led_state_validator.valid?(@admin_locator_led_state)
      admin_power_state_validator = EnumAttributeValidator.new('String', ["Policy", "PowerOn", "PowerOff", "PowerCycle", "HardReset", "Shutdown", "Reboot"])
      return false unless admin_power_state_validator.valid?(@admin_power_state)
      cmos_reset_validator = EnumAttributeValidator.new('String', ["Ready", "Pending", "Reset"])
      return false unless cmos_reset_validator.valid?(@cmos_reset)
      config_state_validator = EnumAttributeValidator.new('String', ["Applied", "Applying", "Failed"])
      return false unless config_state_validator.valid?(@config_state)
      front_panel_lock_state_validator = EnumAttributeValidator.new('String', ["Unlock", "Lock"])
      return false unless front_panel_lock_state_validator.valid?(@front_panel_lock_state)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] class_id Object to be assigned
    def class_id=(class_id)
      validator = EnumAttributeValidator.new('String', ["compute.ServerSetting"])
      unless validator.valid?(class_id)
        fail ArgumentError, "invalid value for \"class_id\", must be one of #{validator.allowable_values}."
      end
      @class_id = class_id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] object_type Object to be assigned
    def object_type=(object_type)
      validator = EnumAttributeValidator.new('String', ["compute.ServerSetting"])
      unless validator.valid?(object_type)
        fail ArgumentError, "invalid value for \"object_type\", must be one of #{validator.allowable_values}."
      end
      @object_type = object_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] admin_locator_led_state Object to be assigned
    def admin_locator_led_state=(admin_locator_led_state)
      validator = EnumAttributeValidator.new('String', ["None", "On", "Off"])
      unless validator.valid?(admin_locator_led_state)
        fail ArgumentError, "invalid value for \"admin_locator_led_state\", must be one of #{validator.allowable_values}."
      end
      @admin_locator_led_state = admin_locator_led_state
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] admin_power_state Object to be assigned
    def admin_power_state=(admin_power_state)
      validator = EnumAttributeValidator.new('String', ["Policy", "PowerOn", "PowerOff", "PowerCycle", "HardReset", "Shutdown", "Reboot"])
      unless validator.valid?(admin_power_state)
        fail ArgumentError, "invalid value for \"admin_power_state\", must be one of #{validator.allowable_values}."
      end
      @admin_power_state = admin_power_state
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] cmos_reset Object to be assigned
    def cmos_reset=(cmos_reset)
      validator = EnumAttributeValidator.new('String', ["Ready", "Pending", "Reset"])
      unless validator.valid?(cmos_reset)
        fail ArgumentError, "invalid value for \"cmos_reset\", must be one of #{validator.allowable_values}."
      end
      @cmos_reset = cmos_reset
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] config_state Object to be assigned
    def config_state=(config_state)
      validator = EnumAttributeValidator.new('String', ["Applied", "Applying", "Failed"])
      unless validator.valid?(config_state)
        fail ArgumentError, "invalid value for \"config_state\", must be one of #{validator.allowable_values}."
      end
      @config_state = config_state
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] front_panel_lock_state Object to be assigned
    def front_panel_lock_state=(front_panel_lock_state)
      validator = EnumAttributeValidator.new('String', ["Unlock", "Lock"])
      unless validator.valid?(front_panel_lock_state)
        fail ArgumentError, "invalid value for \"front_panel_lock_state\", must be one of #{validator.allowable_values}."
      end
      @front_panel_lock_state = front_panel_lock_state
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          class_id == o.class_id &&
          object_type == o.object_type &&
          admin_locator_led_state == o.admin_locator_led_state &&
          admin_power_state == o.admin_power_state &&
          certificates_action == o.certificates_action &&
          cmos_reset == o.cmos_reset &&
          config_state == o.config_state &&
          front_panel_lock_state == o.front_panel_lock_state &&
          name == o.name &&
          one_time_boot_device == o.one_time_boot_device &&
          persistent_memory_operation == o.persistent_memory_operation &&
          server_config == o.server_config &&
          storage_controller_operation == o.storage_controller_operation &&
          storage_physical_drive_operation == o.storage_physical_drive_operation &&
          storage_virtual_drive_operation == o.storage_virtual_drive_operation &&
          locator_led == o.locator_led &&
          registered_device == o.registered_device &&
          running_workflow == o.running_workflow &&
          server == o.server
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [class_id, object_type, admin_locator_led_state, admin_power_state, certificates_action, cmos_reset, config_state, front_panel_lock_state, name, one_time_boot_device, persistent_memory_operation, server_config, storage_controller_operation, storage_physical_drive_operation, storage_virtual_drive_operation, locator_led, registered_device, running_workflow, server].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      ComputeServerSettingAllOf.openapi_types.each_pair do |key, type|
        if attributes[ComputeServerSettingAllOf.attribute_map[key]].nil? && ComputeServerSettingAllOf.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[ComputeServerSettingAllOf.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[ComputeServerSettingAllOf.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[ComputeServerSettingAllOf.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[ComputeServerSettingAllOf.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = IntersightClient.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      ComputeServerSettingAllOf.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = ComputeServerSettingAllOf.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
